import type { TrainingSession } from "./training-session-types";

export const sessionLibrary: TrainingSession[] = [
  // LOW: REGENERATIVO
  { id: "RE1", code: "RE1", name: "Regenerativo", type: "RE", intensity: "low", duration: 1200, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 1200, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Treino regenerativo leve em Z1", structure: [{ id: "s1", phase: "main", label: "Treino Principal", content: "20min Z1", zone: "Z1", durationSeconds: 1200 }], isCustom: false, tags: ["regenerativo", "z1"] },
  { id: "RE2", code: "RE2", name: "Regenerativo", type: "RE", intensity: "low", duration: 1500, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 1500, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Treino regenerativo leve em Z1", structure: [{ id: "s1", phase: "main", label: "Treino Principal", content: "25min Z1", zone: "Z1", durationSeconds: 1500 }], isCustom: false, tags: ["regenerativo", "z1"] },
  { id: "RE3", code: "RE3", name: "Regenerativo", type: "RE", intensity: "low", duration: 1800, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 1800, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Treino regenerativo leve em Z1", structure: [{ id: "s1", phase: "main", label: "Treino Principal", content: "30min Z1", zone: "Z1", durationSeconds: 1800 }], isCustom: false, tags: ["regenerativo", "z1"] },

  // LOW: BASE AERÓBIA
  { id: "BA1", code: "BA1", name: "Base Aeróbia", type: "BA", intensity: "low", duration: 1200, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 600, Z2: 600, Z3: 0, Z4: 0, Z5: 0 }, description: "Base aeróbia Z1+Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1", zone: "Z1", durationSeconds: 300 }, { id: "s2", phase: "main", label: "Treino Principal", content: "10min Z2", zone: "Z2", durationSeconds: 600 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["base aeróbia", "z2"] },
  { id: "BA2", code: "BA2", name: "Base Aeróbia", type: "BA", intensity: "low", duration: 1500, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 600, Z2: 900, Z3: 0, Z4: 0, Z5: 0 }, description: "Base aeróbia Z1+Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1", zone: "Z1", durationSeconds: 300 }, { id: "s2", phase: "main", label: "Treino Principal", content: "15min Z2", zone: "Z2", durationSeconds: 900 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["base aeróbia", "z2"] },
  { id: "BA3", code: "BA3", name: "Base Aeróbia", type: "BA", intensity: "low", duration: 2100, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 600, Z2: 1500, Z3: 0, Z4: 0, Z5: 0 }, description: "Base aeróbia Z1+Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1", zone: "Z1", durationSeconds: 300 }, { id: "s2", phase: "main", label: "Treino Principal", content: "25min Z2", zone: "Z2", durationSeconds: 1500 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["base aeróbia", "z2"] },

  // LOW: INTERVALADO AERÓBIO
  { id: "IAE1", code: "IAE1", name: "Intervalado Aeróbio", type: "IAE", intensity: "low", duration: 3540, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 1740, Z2: 1800, Z3: 0, Z4: 0, Z5: 0 }, description: "Intervalado aeróbio 3×10min Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "10min Z1", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3 x (10min Z2 + 3min Z1)", zone: "Z2", durationSeconds: 1980 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "10min Z1", zone: "Z1", durationSeconds: 600 }], isCustom: false, tags: ["intervalado", "aeróbio", "z2"] },
  { id: "IAE2", code: "IAE2", name: "Intervalado Aeróbio", type: "IAE", intensity: "low", duration: 5340, distance: null, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 3540, Z2: 1800, Z3: 0, Z4: 0, Z5: 0 }, description: "Intervalado aeróbio com recuperação longa", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "15min Z1", zone: "Z1", durationSeconds: 900 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3 x (10min Z2 + 3min Z1)", zone: "Z2", durationSeconds: 1980 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "35min Z1", zone: "Z1", durationSeconds: 2100 }], isCustom: false, tags: ["intervalado", "aeróbio", "z2"] },

  // LOW: LONGÃO
  { id: "LON1", code: "LON1", name: "Longão", type: "LON", intensity: "low", duration: null, distance: 5000, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Longão 5km Z1/Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "2000m Z1", zone: "Z1", distanceMeters: 2000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "2000m Z2", zone: "Z2", distanceMeters: 2000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }], isCustom: false, tags: ["longão", "distância"] },
  { id: "LON2", code: "LON2", name: "Longão", type: "LON", intensity: "low", duration: null, distance: 6000, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Longão 6km Z1/Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "2000m Z1", zone: "Z1", distanceMeters: 2000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3000m Z2", zone: "Z2", distanceMeters: 3000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }], isCustom: false, tags: ["longão", "distância"] },
  { id: "LON3", code: "LON3", name: "Longão", type: "LON", intensity: "low", duration: null, distance: 8000, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Longão 8km Z1/Z2", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "2000m Z1", zone: "Z1", distanceMeters: 2000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "5000m Z2", zone: "Z2", distanceMeters: 5000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }], isCustom: false, tags: ["longão", "distância"] },

  // MODERATE: PROGRESSIVO
  { id: "PRO1", code: "PRO1", name: "Progressivo", type: "PRO", intensity: "moderate", duration: 1800, distance: null, ratioL: 0.833, ratioMH: 0.167, zones: { Z1: 600, Z2: 900, Z3: 300, Z4: 0, Z5: 0 }, description: "Progressivo Z1→Z2→Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1", zone: "Z1", durationSeconds: 300 }, { id: "s2", phase: "main", label: "Treino Principal", content: "15min Z2", zone: "Z2", durationSeconds: 900 }, { id: "s3", phase: "main", label: "Treino Principal", content: "5min Z3 + 5min Z1", zone: "Z3", durationSeconds: 600 }], isCustom: false, tags: ["progressivo", "z3"] },
  { id: "PRO2", code: "PRO2", name: "Progressivo", type: "PRO", intensity: "moderate", duration: 2100, distance: null, ratioL: 0.857, ratioMH: 0.143, zones: { Z1: 600, Z2: 1200, Z3: 300, Z4: 0, Z5: 0 }, description: "Progressivo Z1→Z2→Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1", zone: "Z1", durationSeconds: 300 }, { id: "s2", phase: "main", label: "Treino Principal", content: "20min Z2", zone: "Z2", durationSeconds: 1200 }, { id: "s3", phase: "main", label: "Treino Principal", content: "5min Z3 + 5min Z1", zone: "Z3", durationSeconds: 600 }], isCustom: false, tags: ["progressivo", "z3"] },

  // MODERATE: TEMPO RUN
  { id: "TRU1", code: "TRU1", name: "Tempo Run", type: "TRU", intensity: "moderate", duration: 2100, distance: null, ratioL: 0.571, ratioMH: 0.429, zones: { Z1: 600, Z2: 600, Z3: 900, Z4: 0, Z5: 0 }, description: "Tempo Run bloco contínuo Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "15min Z3", zone: "Z3", durationSeconds: 900 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z2 + 5min Z1", zone: "Z1", durationSeconds: 600 }], isCustom: false, tags: ["tempo run", "z3", "limiar"] },
  { id: "TRU2", code: "TRU2", name: "Tempo Run", type: "TRU", intensity: "moderate", duration: 2280, distance: null, ratioL: 0.526, ratioMH: 0.474, zones: { Z1: 600, Z2: 600, Z3: 1080, Z4: 0, Z5: 0 }, description: "Tempo Run bloco longo Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "18min Z3", zone: "Z3", durationSeconds: 1080 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z2 + 5min Z1", zone: "Z1", durationSeconds: 600 }], isCustom: false, tags: ["tempo run", "z3", "limiar"] },

  // MODERATE: INTERVALADO MODERADO
  { id: "IAM1", code: "IAM1", name: "Intervalado Moderado", type: "IAM", intensity: "moderate", duration: 2820, distance: null, ratioL: 0.681, ratioMH: 0.319, zones: { Z1: 1320, Z2: 600, Z3: 900, Z4: 0, Z5: 0 }, description: "Intervalado moderado 3×5min Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3 x (5min Z3 + 3min Z1)", zone: "Z3", durationSeconds: 1440 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z2 + 5min Z1", zone: "Z1", durationSeconds: 600 }], isCustom: false, tags: ["intervalado", "moderado", "z3"] },
  { id: "IAM2", code: "IAM2", name: "Intervalado Moderado", type: "IAM", intensity: "moderate", duration: 3120, distance: null, ratioL: 0.615, ratioMH: 0.385, zones: { Z1: 1320, Z2: 600, Z3: 1200, Z4: 0, Z5: 0 }, description: "Intervalado moderado 4×5min Z3", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "4 x (5min Z3 + 3min Z1)", zone: "Z3", durationSeconds: 1920 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z2 + 5min Z1", zone: "Z1", durationSeconds: 600 }], isCustom: false, tags: ["intervalado", "moderado", "z3"] },

  // MODERATE: PROGRESSIVO LONGO
  { id: "PRL1", code: "PRL1", name: "Progressivo Longo", type: "PRL", intensity: "moderate", duration: null, distance: 13000, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Progressivo longo 13km", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "10000m Z2", zone: "Z2", distanceMeters: 10000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "2000m Z3", zone: "Z3", distanceMeters: 2000 }], isCustom: false, tags: ["progressivo", "longo", "distância"] },
  { id: "PRL2", code: "PRL2", name: "Progressivo Longo", type: "PRL", intensity: "moderate", duration: null, distance: 16000, ratioL: 1.0, ratioMH: 0.0, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "Progressivo longo 16km", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "13000m Z2", zone: "Z2", distanceMeters: 13000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "2000m Z3", zone: "Z3", distanceMeters: 2000 }], isCustom: false, tags: ["progressivo", "longo", "distância"] },

  // MODERATE: CORRIDA RÁPIDA LONGA
  { id: "CRL1", code: "CRL1", name: "Corrida Rápida Longa", type: "CRL", intensity: "moderate", duration: null, distance: 6000, ratioL: 0.5, ratioMH: 0.5, zones: { Z1: 0, Z2: 0, Z3: 0, Z4: 0, Z5: 0 }, description: "6km com aceleração por distância", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }, { id: "s2", phase: "main", label: "Treino Principal", content: "4000m Z2", zone: "Z2", distanceMeters: 4000 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "1000m Z1", zone: "Z1", distanceMeters: 1000 }], isCustom: false, tags: ["corrida rápida", "longa", "distância"] },

  // HIGH: CORRIDA RÁPIDA
  { id: "CRAP1", code: "CRAP1", name: "Corrida Rápida", type: "PRO", intensity: "high", duration: 1620, distance: null, ratioL: 0.778, ratioMH: 0.222, zones: { Z1: 960, Z2: 300, Z3: 0, Z4: 360, Z5: 0 }, description: "Tiros em Z4 3×2min", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3 x (2min Z4 + 2min Z1)", zone: "Z4", durationSeconds: 720 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["corrida rápida", "z4"] },
  { id: "CRAP2", code: "CRAP2", name: "Corrida Rápida", type: "PRO", intensity: "high", duration: 1800, distance: null, ratioL: 0.833, ratioMH: 0.167, zones: { Z1: 1200, Z2: 300, Z3: 0, Z4: 300, Z5: 0 }, description: "Tiros em Z4 5×1min", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "5 x (1min Z4 + 2min Z1)", zone: "Z4", durationSeconds: 900 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["corrida rápida", "z4"] },

  // HIGH: SUBIDAS
  { id: "SUB1", code: "SUB1", name: "Subidas", type: "SUB", intensity: "high", duration: 1620, distance: null, ratioL: 0.889, ratioMH: 0.111, zones: { Z1: 1140, Z2: 300, Z3: 0, Z4: 0, Z5: 180 }, description: "Subidas explosivas 6×30seg Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "6 x (30seg Z5 + 1min30seg Z1)", zone: "Z5", durationSeconds: 720 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["subidas", "z5", "explosivo"] },
  { id: "SUB2", code: "SUB2", name: "Subidas", type: "SUB", intensity: "high", duration: 1860, distance: null, ratioL: 0.871, ratioMH: 0.129, zones: { Z1: 1380, Z2: 300, Z3: 0, Z4: 0, Z5: 240 }, description: "Subidas explosivas 8×30seg Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "8 x (30seg Z5 + 1min30seg Z1)", zone: "Z5", durationSeconds: 960 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["subidas", "z5", "explosivo"] },

  // HIGH: INTERVALADO INTENSO CURTO
  { id: "IAI1", code: "IAI1", name: "Intervalado Intenso Curto", type: "IAI", intensity: "high", duration: 1980, distance: null, ratioL: 0.818, ratioMH: 0.182, zones: { Z1: 1320, Z2: 300, Z3: 0, Z4: 0, Z5: 360 }, description: "6×1min Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "6 x (1min Z5 + 2min Z1)", zone: "Z5", durationSeconds: 1080 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["intervalado", "intenso", "z5", "curto"] },
  { id: "IAI2", code: "IAI2", name: "Intervalado Intenso Curto", type: "IAI", intensity: "high", duration: 2340, distance: null, ratioL: 0.795, ratioMH: 0.205, zones: { Z1: 1560, Z2: 300, Z3: 0, Z4: 0, Z5: 480 }, description: "8×1min Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "8 x (1min Z5 + 2min Z1)", zone: "Z5", durationSeconds: 1440 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["intervalado", "intenso", "z5", "curto"] },

  // HIGH: INTERVALADO INTENSO LONGO
  { id: "IAL1", code: "IAL1", name: "Intervalado Intenso Longo", type: "IAL", intensity: "high", duration: 1800, distance: null, ratioL: 0.7, ratioMH: 0.3, zones: { Z1: 960, Z2: 300, Z3: 0, Z4: 540, Z5: 0 }, description: "3×3min Z4", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3 x (3min Z4 + 2min Z1)", zone: "Z4", durationSeconds: 900 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["intervalado", "intenso", "z4", "longo"] },
  { id: "IAL2", code: "IAL2", name: "Intervalado Intenso Longo", type: "IAL", intensity: "high", duration: 2100, distance: null, ratioL: 0.657, ratioMH: 0.343, zones: { Z1: 1080, Z2: 300, Z3: 0, Z4: 720, Z5: 0 }, description: "4×3min Z4", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2", zone: "Z1", durationSeconds: 600 }, { id: "s2", phase: "main", label: "Treino Principal", content: "4 x (3min Z4 + 2min Z1)", zone: "Z4", durationSeconds: 1200 }, { id: "s3", phase: "recovery", label: "Recuperação", content: "5min Z1", zone: "Z1", durationSeconds: 300 }], isCustom: false, tags: ["intervalado", "intenso", "z4", "longo"] },

  // HIGH: INTERVALADO MISTO
  { id: "IMI1", code: "IMI1", name: "Intervalado Misto", type: "IMI", intensity: "high", duration: 2160, distance: null, ratioL: 0.639, ratioMH: 0.361, zones: { Z1: 1080, Z2: 300, Z3: 300, Z4: 360, Z5: 120 }, description: "Misto Z3+Z4+Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2 + 1min Z5 + 2min Z1", zone: "Z1", durationSeconds: 780 }, { id: "s2", phase: "main", label: "Treino Principal", content: "3min Z4 + 2min Z1 + 5min Z3 + 2min Z1", zone: "Z4", durationSeconds: 720 }, { id: "s3", phase: "main", label: "Treino Principal", content: "3min Z4 + 2min Z1 + 1min Z5 + 5min Z1", zone: "Z4", durationSeconds: 660 }], isCustom: false, tags: ["misto", "z4", "z5"] },
  { id: "IMI2", code: "IMI2", name: "Intervalado Misto", type: "IMI", intensity: "high", duration: 2760, distance: null, ratioL: 0.5, ratioMH: 0.5, zones: { Z1: 1080, Z2: 300, Z3: 600, Z4: 600, Z5: 180 }, description: "Misto longo Z3+Z4+Z5", structure: [{ id: "s1", phase: "warmup", label: "Aquecimento", content: "5min Z1 + 5min Z2 + 1min30seg Z5 + 2min Z1", zone: "Z1", durationSeconds: 810 }, { id: "s2", phase: "main", label: "Treino Principal", content: "5min Z4 + 2min Z1 + 10min Z3 + 2min Z1", zone: "Z4", durationSeconds: 1140 }, { id: "s3", phase: "main", label: "Treino Principal", content: "5min Z4 + 2min Z1 + 1min30seg Z5 + 5min Z1", zone: "Z4", durationSeconds: 810 }], isCustom: false, tags: ["misto", "z4", "z5", "longo"] },
];
