/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroTreinadorRouteImport } from './routes/cadastro-treinador'
import { Route as CadastroCorredorRouteImport } from './routes/cadastro-corredor'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeste3kmRouteImport } from './routes/_authenticated/teste-3km'
import { Route as AuthenticatedPlanilha5kmRouteImport } from './routes/_authenticated/planilha-5km'
import { Route as AuthenticatedPlanilha42kmRouteImport } from './routes/_authenticated/planilha-42km'
import { Route as AuthenticatedPlanilha21kmRouteImport } from './routes/_authenticated/planilha-21km'
import { Route as AuthenticatedPlanilha10kmRouteImport } from './routes/_authenticated/planilha-10km'
import { Route as AuthenticatedMinhaMarcaRouteImport } from './routes/_authenticated/minha-marca'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCorredorIndexRouteImport } from './routes/_authenticated/corredor.index'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedCorredorOnboardingRouteImport } from './routes/_authenticated/corredor.onboarding'
import { Route as AuthenticatedCorredorAvaliacaoRouteImport } from './routes/_authenticated/corredor.avaliacao'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated/alunos.novo'
import { Route as AuthenticatedAlunosStudentIdRouteImport } from './routes/_authenticated/alunos.$studentId'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTreinadoresRouteImport } from './routes/_authenticated/admin.treinadores'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAlunosRouteImport } from './routes/_authenticated/admin.alunos'
import { Route as AuthenticatedCorredorPlanilhaIndexRouteImport } from './routes/_authenticated/corredor.planilha.index'
import { Route as AuthenticatedIntegracoesStravaCallbackRouteImport } from './routes/_authenticated/integracoes.strava.callback'
import { Route as AuthenticatedCorredorPlanilhaNovaRouteImport } from './routes/_authenticated/corredor.planilha.nova'
import { Route as AuthenticatedAlunosStudentIdPrescricaoPlanIdRouteImport } from './routes/_authenticated/alunos.$studentId.prescricao.$planId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroTreinadorRoute = CadastroTreinadorRouteImport.update({
  id: '/cadastro-treinador',
  path: '/cadastro-treinador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroCorredorRoute = CadastroCorredorRouteImport.update({
  id: '/cadastro-corredor',
  path: '/cadastro-corredor',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeste3kmRoute = AuthenticatedTeste3kmRouteImport.update({
  id: '/teste-3km',
  path: '/teste-3km',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanilha5kmRoute =
  AuthenticatedPlanilha5kmRouteImport.update({
    id: '/planilha-5km',
    path: '/planilha-5km',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanilha42kmRoute =
  AuthenticatedPlanilha42kmRouteImport.update({
    id: '/planilha-42km',
    path: '/planilha-42km',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanilha21kmRoute =
  AuthenticatedPlanilha21kmRouteImport.update({
    id: '/planilha-21km',
    path: '/planilha-21km',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanilha10kmRoute =
  AuthenticatedPlanilha10kmRouteImport.update({
    id: '/planilha-10km',
    path: '/planilha-10km',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhaMarcaRoute = AuthenticatedMinhaMarcaRouteImport.update({
  id: '/minha-marca',
  path: '/minha-marca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorredorIndexRoute =
  AuthenticatedCorredorIndexRouteImport.update({
    id: '/corredor/',
    path: '/corredor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCorredorOnboardingRoute =
  AuthenticatedCorredorOnboardingRouteImport.update({
    id: '/corredor/onboarding',
    path: '/corredor/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorredorAvaliacaoRoute =
  AuthenticatedCorredorAvaliacaoRouteImport.update({
    id: '/corredor/avaliacao',
    path: '/corredor/avaliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosStudentIdRoute =
  AuthenticatedAlunosStudentIdRouteImport.update({
    id: '/alunos/$studentId',
    path: '/alunos/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTreinadoresRoute =
  AuthenticatedAdminTreinadoresRouteImport.update({
    id: '/treinadores',
    path: '/treinadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlunosRoute =
  AuthenticatedAdminAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCorredorPlanilhaIndexRoute =
  AuthenticatedCorredorPlanilhaIndexRouteImport.update({
    id: '/corredor/planilha/',
    path: '/corredor/planilha/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegracoesStravaCallbackRoute =
  AuthenticatedIntegracoesStravaCallbackRouteImport.update({
    id: '/integracoes/strava/callback',
    path: '/integracoes/strava/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorredorPlanilhaNovaRoute =
  AuthenticatedCorredorPlanilhaNovaRouteImport.update({
    id: '/corredor/planilha/nova',
    path: '/corredor/planilha/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute =
  AuthenticatedAlunosStudentIdPrescricaoPlanIdRouteImport.update({
    id: '/prescricao/$planId',
    path: '/prescricao/$planId',
    getParentRoute: () => AuthenticatedAlunosStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-corredor': typeof CadastroCorredorRoute
  '/cadastro-treinador': typeof CadastroTreinadorRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/minha-marca': typeof AuthenticatedMinhaMarcaRoute
  '/planilha-10km': typeof AuthenticatedPlanilha10kmRoute
  '/planilha-21km': typeof AuthenticatedPlanilha21kmRoute
  '/planilha-42km': typeof AuthenticatedPlanilha42kmRoute
  '/planilha-5km': typeof AuthenticatedPlanilha5kmRoute
  '/teste-3km': typeof AuthenticatedTeste3kmRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/treinadores': typeof AuthenticatedAdminTreinadoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRouteWithChildren
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/corredor/avaliacao': typeof AuthenticatedCorredorAvaliacaoRoute
  '/corredor/onboarding': typeof AuthenticatedCorredorOnboardingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/corredor/': typeof AuthenticatedCorredorIndexRoute
  '/corredor/planilha/nova': typeof AuthenticatedCorredorPlanilhaNovaRoute
  '/integracoes/strava/callback': typeof AuthenticatedIntegracoesStravaCallbackRoute
  '/corredor/planilha/': typeof AuthenticatedCorredorPlanilhaIndexRoute
  '/alunos/$studentId/prescricao/$planId': typeof AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-corredor': typeof CadastroCorredorRoute
  '/cadastro-treinador': typeof CadastroTreinadorRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/minha-marca': typeof AuthenticatedMinhaMarcaRoute
  '/planilha-10km': typeof AuthenticatedPlanilha10kmRoute
  '/planilha-21km': typeof AuthenticatedPlanilha21kmRoute
  '/planilha-42km': typeof AuthenticatedPlanilha42kmRoute
  '/planilha-5km': typeof AuthenticatedPlanilha5kmRoute
  '/teste-3km': typeof AuthenticatedTeste3kmRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/treinadores': typeof AuthenticatedAdminTreinadoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRouteWithChildren
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/corredor/avaliacao': typeof AuthenticatedCorredorAvaliacaoRoute
  '/corredor/onboarding': typeof AuthenticatedCorredorOnboardingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/corredor': typeof AuthenticatedCorredorIndexRoute
  '/corredor/planilha/nova': typeof AuthenticatedCorredorPlanilhaNovaRoute
  '/integracoes/strava/callback': typeof AuthenticatedIntegracoesStravaCallbackRoute
  '/corredor/planilha': typeof AuthenticatedCorredorPlanilhaIndexRoute
  '/alunos/$studentId/prescricao/$planId': typeof AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-corredor': typeof CadastroCorredorRoute
  '/cadastro-treinador': typeof CadastroTreinadorRoute
  '/login': typeof LoginRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/minha-marca': typeof AuthenticatedMinhaMarcaRoute
  '/_authenticated/planilha-10km': typeof AuthenticatedPlanilha10kmRoute
  '/_authenticated/planilha-21km': typeof AuthenticatedPlanilha21kmRoute
  '/_authenticated/planilha-42km': typeof AuthenticatedPlanilha42kmRoute
  '/_authenticated/planilha-5km': typeof AuthenticatedPlanilha5kmRoute
  '/_authenticated/teste-3km': typeof AuthenticatedTeste3kmRoute
  '/_authenticated/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/treinadores': typeof AuthenticatedAdminTreinadoresRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRouteWithChildren
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/corredor/avaliacao': typeof AuthenticatedCorredorAvaliacaoRoute
  '/_authenticated/corredor/onboarding': typeof AuthenticatedCorredorOnboardingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/corredor/': typeof AuthenticatedCorredorIndexRoute
  '/_authenticated/corredor/planilha/nova': typeof AuthenticatedCorredorPlanilhaNovaRoute
  '/_authenticated/integracoes/strava/callback': typeof AuthenticatedIntegracoesStravaCallbackRoute
  '/_authenticated/corredor/planilha/': typeof AuthenticatedCorredorPlanilhaIndexRoute
  '/_authenticated/alunos/$studentId/prescricao/$planId': typeof AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/cadastro'
    | '/cadastro-corredor'
    | '/cadastro-treinador'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/recuperar-senha'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/minha-conta'
    | '/minha-marca'
    | '/planilha-10km'
    | '/planilha-21km'
    | '/planilha-42km'
    | '/planilha-5km'
    | '/teste-3km'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/treinadores'
    | '/admin/usuarios'
    | '/alunos/$studentId'
    | '/alunos/novo'
    | '/corredor/avaliacao'
    | '/corredor/onboarding'
    | '/admin/'
    | '/alunos/'
    | '/corredor/'
    | '/corredor/planilha/nova'
    | '/integracoes/strava/callback'
    | '/corredor/planilha/'
    | '/alunos/$studentId/prescricao/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/cadastro'
    | '/cadastro-corredor'
    | '/cadastro-treinador'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/recuperar-senha'
    | '/signup'
    | '/dashboard'
    | '/minha-conta'
    | '/minha-marca'
    | '/planilha-10km'
    | '/planilha-21km'
    | '/planilha-42km'
    | '/planilha-5km'
    | '/teste-3km'
    | '/admin/alunos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/treinadores'
    | '/admin/usuarios'
    | '/alunos/$studentId'
    | '/alunos/novo'
    | '/corredor/avaliacao'
    | '/corredor/onboarding'
    | '/admin'
    | '/alunos'
    | '/corredor'
    | '/corredor/planilha/nova'
    | '/integracoes/strava/callback'
    | '/corredor/planilha'
    | '/alunos/$studentId/prescricao/$planId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/cadastro'
    | '/cadastro-corredor'
    | '/cadastro-treinador'
    | '/login'
    | '/nova-senha'
    | '/onboarding'
    | '/recuperar-senha'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/minha-conta'
    | '/_authenticated/minha-marca'
    | '/_authenticated/planilha-10km'
    | '/_authenticated/planilha-21km'
    | '/_authenticated/planilha-42km'
    | '/_authenticated/planilha-5km'
    | '/_authenticated/teste-3km'
    | '/_authenticated/admin/alunos'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/treinadores'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/alunos/$studentId'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/corredor/avaliacao'
    | '/_authenticated/corredor/onboarding'
    | '/_authenticated/admin/'
    | '/_authenticated/alunos/'
    | '/_authenticated/corredor/'
    | '/_authenticated/corredor/planilha/nova'
    | '/_authenticated/integracoes/strava/callback'
    | '/_authenticated/corredor/planilha/'
    | '/_authenticated/alunos/$studentId/prescricao/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  CadastroRoute: typeof CadastroRoute
  CadastroCorredorRoute: typeof CadastroCorredorRoute
  CadastroTreinadorRoute: typeof CadastroTreinadorRoute
  LoginRoute: typeof LoginRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  OnboardingRoute: typeof OnboardingRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-treinador': {
      id: '/cadastro-treinador'
      path: '/cadastro-treinador'
      fullPath: '/cadastro-treinador'
      preLoaderRoute: typeof CadastroTreinadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-corredor': {
      id: '/cadastro-corredor'
      path: '/cadastro-corredor'
      fullPath: '/cadastro-corredor'
      preLoaderRoute: typeof CadastroCorredorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teste-3km': {
      id: '/_authenticated/teste-3km'
      path: '/teste-3km'
      fullPath: '/teste-3km'
      preLoaderRoute: typeof AuthenticatedTeste3kmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planilha-5km': {
      id: '/_authenticated/planilha-5km'
      path: '/planilha-5km'
      fullPath: '/planilha-5km'
      preLoaderRoute: typeof AuthenticatedPlanilha5kmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planilha-42km': {
      id: '/_authenticated/planilha-42km'
      path: '/planilha-42km'
      fullPath: '/planilha-42km'
      preLoaderRoute: typeof AuthenticatedPlanilha42kmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planilha-21km': {
      id: '/_authenticated/planilha-21km'
      path: '/planilha-21km'
      fullPath: '/planilha-21km'
      preLoaderRoute: typeof AuthenticatedPlanilha21kmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planilha-10km': {
      id: '/_authenticated/planilha-10km'
      path: '/planilha-10km'
      fullPath: '/planilha-10km'
      preLoaderRoute: typeof AuthenticatedPlanilha10kmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-marca': {
      id: '/_authenticated/minha-marca'
      path: '/minha-marca'
      fullPath: '/minha-marca'
      preLoaderRoute: typeof AuthenticatedMinhaMarcaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corredor/': {
      id: '/_authenticated/corredor/'
      path: '/corredor'
      fullPath: '/corredor/'
      preLoaderRoute: typeof AuthenticatedCorredorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/corredor/onboarding': {
      id: '/_authenticated/corredor/onboarding'
      path: '/corredor/onboarding'
      fullPath: '/corredor/onboarding'
      preLoaderRoute: typeof AuthenticatedCorredorOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corredor/avaliacao': {
      id: '/_authenticated/corredor/avaliacao'
      path: '/corredor/avaliacao'
      fullPath: '/corredor/avaliacao'
      preLoaderRoute: typeof AuthenticatedCorredorAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$studentId': {
      id: '/_authenticated/alunos/$studentId'
      path: '/alunos/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AuthenticatedAlunosStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/treinadores': {
      id: '/_authenticated/admin/treinadores'
      path: '/treinadores'
      fullPath: '/admin/treinadores'
      preLoaderRoute: typeof AuthenticatedAdminTreinadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alunos': {
      id: '/_authenticated/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/corredor/planilha/': {
      id: '/_authenticated/corredor/planilha/'
      path: '/corredor/planilha'
      fullPath: '/corredor/planilha/'
      preLoaderRoute: typeof AuthenticatedCorredorPlanilhaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes/strava/callback': {
      id: '/_authenticated/integracoes/strava/callback'
      path: '/integracoes/strava/callback'
      fullPath: '/integracoes/strava/callback'
      preLoaderRoute: typeof AuthenticatedIntegracoesStravaCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corredor/planilha/nova': {
      id: '/_authenticated/corredor/planilha/nova'
      path: '/corredor/planilha/nova'
      fullPath: '/corredor/planilha/nova'
      preLoaderRoute: typeof AuthenticatedCorredorPlanilhaNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$studentId/prescricao/$planId': {
      id: '/_authenticated/alunos/$studentId/prescricao/$planId'
      path: '/prescricao/$planId'
      fullPath: '/alunos/$studentId/prescricao/$planId'
      preLoaderRoute: typeof AuthenticatedAlunosStudentIdPrescricaoPlanIdRouteImport
      parentRoute: typeof AuthenticatedAlunosStudentIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlunosRoute: typeof AuthenticatedAdminAlunosRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminTreinadoresRoute: typeof AuthenticatedAdminTreinadoresRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlunosRoute: AuthenticatedAdminAlunosRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminTreinadoresRoute: AuthenticatedAdminTreinadoresRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAlunosStudentIdRouteChildren {
  AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute: typeof AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute
}

const AuthenticatedAlunosStudentIdRouteChildren: AuthenticatedAlunosStudentIdRouteChildren =
  {
    AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute:
      AuthenticatedAlunosStudentIdPrescricaoPlanIdRoute,
  }

const AuthenticatedAlunosStudentIdRouteWithChildren =
  AuthenticatedAlunosStudentIdRoute._addFileChildren(
    AuthenticatedAlunosStudentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedMinhaMarcaRoute: typeof AuthenticatedMinhaMarcaRoute
  AuthenticatedPlanilha10kmRoute: typeof AuthenticatedPlanilha10kmRoute
  AuthenticatedPlanilha21kmRoute: typeof AuthenticatedPlanilha21kmRoute
  AuthenticatedPlanilha42kmRoute: typeof AuthenticatedPlanilha42kmRoute
  AuthenticatedPlanilha5kmRoute: typeof AuthenticatedPlanilha5kmRoute
  AuthenticatedTeste3kmRoute: typeof AuthenticatedTeste3kmRoute
  AuthenticatedAlunosStudentIdRoute: typeof AuthenticatedAlunosStudentIdRouteWithChildren
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedCorredorAvaliacaoRoute: typeof AuthenticatedCorredorAvaliacaoRoute
  AuthenticatedCorredorOnboardingRoute: typeof AuthenticatedCorredorOnboardingRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedCorredorIndexRoute: typeof AuthenticatedCorredorIndexRoute
  AuthenticatedCorredorPlanilhaNovaRoute: typeof AuthenticatedCorredorPlanilhaNovaRoute
  AuthenticatedIntegracoesStravaCallbackRoute: typeof AuthenticatedIntegracoesStravaCallbackRoute
  AuthenticatedCorredorPlanilhaIndexRoute: typeof AuthenticatedCorredorPlanilhaIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedMinhaMarcaRoute: AuthenticatedMinhaMarcaRoute,
  AuthenticatedPlanilha10kmRoute: AuthenticatedPlanilha10kmRoute,
  AuthenticatedPlanilha21kmRoute: AuthenticatedPlanilha21kmRoute,
  AuthenticatedPlanilha42kmRoute: AuthenticatedPlanilha42kmRoute,
  AuthenticatedPlanilha5kmRoute: AuthenticatedPlanilha5kmRoute,
  AuthenticatedTeste3kmRoute: AuthenticatedTeste3kmRoute,
  AuthenticatedAlunosStudentIdRoute:
    AuthenticatedAlunosStudentIdRouteWithChildren,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedCorredorAvaliacaoRoute: AuthenticatedCorredorAvaliacaoRoute,
  AuthenticatedCorredorOnboardingRoute: AuthenticatedCorredorOnboardingRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedCorredorIndexRoute: AuthenticatedCorredorIndexRoute,
  AuthenticatedCorredorPlanilhaNovaRoute:
    AuthenticatedCorredorPlanilhaNovaRoute,
  AuthenticatedIntegracoesStravaCallbackRoute:
    AuthenticatedIntegracoesStravaCallbackRoute,
  AuthenticatedCorredorPlanilhaIndexRoute:
    AuthenticatedCorredorPlanilhaIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  CadastroRoute: CadastroRoute,
  CadastroCorredorRoute: CadastroCorredorRoute,
  CadastroTreinadorRoute: CadastroTreinadorRoute,
  LoginRoute: LoginRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  OnboardingRoute: OnboardingRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
